import {
  districtDiagnostics,
  generateNewSeed,
  generationState,
  retryDistrictPlan,
  retryFullGeneration,
  retryGeneratedWalls,
  retryGeometry,
  type GenerationFailure,
  type GenerationState
} from "../../adapter/canvas.js";
import { escapeHTML, generationComponentLabel } from "./shared.js";
import type { WorkspaceContext, WorkspaceModule } from "./types.js";

export type DiagnosticRetry = "walls" | "plan" | "geometry" | "same-seed" | "new-seed";

export interface DiagnosticView {
  severity: "error" | "warning";
  message: string;
  subsystem: string;
  retry: DiagnosticRetry | null;
  /** Stable object/override/site identity when the diagnostic can name one. */
  affectedId?: string;
  /** Multiple affected identities are retained without exposing raw diagnostic data. */
  affectedIds?: string[];
  /** Number of orphaned architecture overrides represented by this entry. */
  orphanedCount?: number;
}

const USER_FACING_SUBSYSTEMS: Record<string, true> = {
  architecture: true,
  city: true,
  "chunk-cache": true,
  districts: true,
  editor: true,
  geometry: true,
  generation: true,
  objects: true,
  "plan-cache": true,
  roads: true,
  save: true,
  "stale-editor": true,
  terrain: true,
  walls: true
};

function text(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const candidate = value.trim();
  return candidate.length === 0 ? null : candidate;
}


function identityList(raw: Record<string, unknown>): string[] {
  const values: unknown[] = [];
  for (const key of ["affectedIds", "objectIds", "siteIds", "targetIds", "orphanedOverrides"]) {
    if (Array.isArray(raw[key])) values.push(...raw[key]);
  }
  for (const key of ["affectedId", "objectId", "siteId", "targetId", "identity", "id"]) {
    if (raw[key] !== undefined) values.push(raw[key]);
  }
  const result: string[] = [];
  for (const value of values) {
    const candidate = typeof value === "object" && value !== null
      ? text((value as Record<string, unknown>).id)
      : text(value);
    if (candidate !== null && !result.includes(candidate)) result.push(candidate);
  }
  return result;
}

function identityFromMessage(message: string): string | null {
  // Diagnostics generated by the architecture planner deliberately quote the stable
  // target ID. Keep this narrow so revisions, epochs, and implementation tokens never
  // become apparent object identities in the UI.
  const match = message.match(/(?:override|object|site|building|place|landmark)\s+"([^"]+)"/i);
  return match?.[1] ?? null;
}

function orphanCount(raw: Record<string, unknown>, kind: string | null, ids: readonly string[]): number | null {
  const explicit = [raw.orphanedOverrideCount, raw.orphanCount, raw.orphanedCount]
    .find((value): value is number => typeof value === "number" && Number.isInteger(value) && value > 0);
  if (explicit !== undefined) return explicit;
  if (Array.isArray(raw.orphanedOverrides)) {
    const count = raw.orphanedOverrides.filter((value) => text(value) !== null).length;
    if (count > 0) return count;
  }
  if (
    kind !== null &&
    (kind.includes("orphan") || kind.includes("override")) &&
    (raw.subsystem === "architecture" || raw.subsystem === "objects")
  ) {
    return Math.max(1, ids.length);
  }
  return null;
}

function retryOf(raw: unknown): DiagnosticRetry | null {
  return raw === "walls" || raw === "plan" || raw === "geometry" || raw === "same-seed" || raw === "new-seed" ? raw : null;
}

/** Reduces one raw diagnostic entry to the user-facing view; drops developer internals. */
export function sanitizeDiagnosticEntry(raw: unknown): DiagnosticView | null {
  if (typeof raw !== "object" || raw === null) return null;
  const record = raw as Record<string, unknown>;
  const rawMessage = text(record.message) ?? text(record.reason);
  const rawKind = text(record.kind)?.toLowerCase() ?? text(record.type)?.toLowerCase() ?? null;
  const rawSubsystemHint = text(record.subsystem);
  const ids = identityList(record);
  const architectureSignal = rawSubsystemHint === "architecture" || rawSubsystemHint === "objects";
  const architectureMessage = rawMessage !== null && /\barchitecture\s+override\b/i.test(rawMessage);
  const orphanMessage = rawMessage !== null && /\borphan(?:ed)?\b/i.test(rawMessage);
  const architectureOrphan = (
    architectureSignal && (
      rawKind?.includes("orphan") === true
      || rawKind?.includes("override") === true
      || orphanMessage
      || Array.isArray(record.orphanedOverrides)
      || (typeof record.orphanedOverrideCount === "number" && record.orphanedOverrideCount > 0)
      || (typeof record.orphanCount === "number" && record.orphanCount > 0)
    )
  ) || rawKind?.includes("orphan") === true || architectureMessage;
  const message = rawMessage ?? (
    rawKind?.includes("stale") === true
      ? "This edit is stale because the city changed. Reopen the object and retry."
      : rawKind?.includes("geometry") === true
        ? "The object geometry is invalid and was not saved."
        : architectureOrphan
          ? "An architecture override is orphaned and was not remapped."
          : null
  );
  if (message === null) return null;

  const parsedId = identityFromMessage(message);
  if (parsedId !== null && !ids.includes(parsedId)) ids.push(parsedId);
  const retry = retryOf(record.retry);
  const rawSubsystem = text(record.subsystem);
  const subsystem = architectureOrphan
    ? "architecture"
    : rawSubsystem === "stale-editor"
      ? "editor"
      : rawSubsystem !== null && USER_FACING_SUBSYSTEMS[rawSubsystem] === true
        ? rawSubsystem
        : rawKind?.includes("stale") === true
          ? "editor"
          : rawKind?.includes("geometry") === true
            ? "geometry"
            : retry ?? "city";
  const orphaned = orphanCount(record, rawKind, ids) ?? (architectureOrphan ? 1 : null);
  const severity = rawKind?.includes("stale") === true || rawKind?.includes("geometry") === true
    ? "error"
    : record.severity === "warning"
      || rawKind === "degraded"
      || orphaned !== null
      || retry === "walls"
      || retry === "plan"
      || retry === "geometry"
      ? "warning"
      : "error";
  const view: DiagnosticView = { severity, message, subsystem, retry };
  if (ids.length === 1) view.affectedId = ids[0];
  else if (ids.length > 1) view.affectedIds = ids;
  if (orphaned !== null) view.orphanedCount = orphaned;
  return view;
}

export function diagnosticViews(entries: readonly Record<string, unknown>[]): DiagnosticView[] {
  const views: DiagnosticView[] = [];
  for (const entry of entries) {
    const view = sanitizeDiagnosticEntry(entry);
    if (view !== null) views.push(view);
  }
  return views;
}

/** Any actionable entry (one with a retry) means the Diagnostics tab needs a badge. */
export function hasActionableDiagnosticViews(views: readonly DiagnosticView[]): boolean {
  return views.some((view) => view.retry !== null);
}

/** Decorative degradation specifically: generated walls were not fully rebuilt. */
export function hasWallRetry(views: readonly DiagnosticView[]): boolean {
  return views.some((view) => view.retry === "walls");
}

export function diagnosticEntries(): Array<Record<string, unknown>> {
  try {
    const value = districtDiagnostics();
    return Array.isArray(value) ? value : [];
  } catch {
    return [];
  }
}

/** Shell badge: any durable warning/error means Diagnostics needs the GM's attention. */
export function diagnosticsWarningActive(): boolean {
  try {
    const state = generationState();
    if (state.phase === "failed" && state.failure !== null) return true;
    return diagnosticViews(districtDiagnostics()).length > 0;
  } catch {
    return false;
  }

}
/** Decorative degradation note on the Generate tray (spec §17.7). */
export function wallRetryWarningActive(): boolean {
  return hasWallRetry(diagnosticViews(districtDiagnostics()));
}

function retryButtonHTML(view: DiagnosticView, busy = false): string {
  const action = view.retry === "walls"
    ? "diagnostics-retry-walls"
    : view.retry === "plan"
      ? "diagnostics-retry-plan"
      : view.retry === "geometry"
        ? "diagnostics-retry-geometry"
        : view.retry === "same-seed"
          ? "diagnostics-retry-same-seed"
          : "diagnostics-retry-new-seed";
  const label = view.retry === "walls"
    ? "Retry generated walls"
    : view.retry === "plan"
      ? "Retry district planning"
      : view.retry === "geometry"
        ? "Retry rendering"
        : view.retry === "same-seed"
          ? "Retry Same Seed"
          : "Generate New Seed";
  const disabled = busy ? " disabled" : "";
  return `<button type="button" aria-label="${label}" data-action="${action}"${disabled}>${label}</button>`;
}

function diagnosticIdentityHTML(view: DiagnosticView): string {
  const ids = view.affectedIds ?? (view.affectedId === undefined ? [] : [view.affectedId]);
  if (ids.length === 0) return "";
  const label = ids.length === 1 ? "Affected object/site" : "Affected objects/sites";
  return `<span class="nixie-diagnostic-identity">${label}: ${ids.map((id) => escapeHTML(id)).join(", ")}</span>`;
}

function orphanSummaryHTML(views: readonly DiagnosticView[]): string {
  const count = views.reduce((total, view) => total + (view.orphanedCount ?? 0), 0);
  if (count === 0) return "";
  const noun = count === 1 ? "override" : "overrides";
  return `<p class="nixie-note nixie-diagnostic-orphans" data-status="architecture-orphans"><strong>Architecture:</strong> ${count} orphaned ${noun} were not remapped.</p>`;
}

function failureSectionHTML(failure: GenerationFailure, busy = false): string {
  const disabled = (allowed: boolean): string => !allowed || busy ? " disabled" : "";
  return `<div data-panel="generation-failure">
    <h4>Structural generation failure</h4>
    <p>${escapeHTML(failure.error)}</p>
    <p class="nixie-note">Failing component: ${escapeHTML(generationComponentLabel(failure.component))}. No complete city was committed; the Scene flag stays clear until a retry succeeds.</p>
    <div class="form-footer">
      <button type="button" aria-label="Retry Same Seed" data-action="diagnostics-retry-same-seed"${disabled(failure.canRetrySameSeed)}>Retry Same Seed</button>
      <button type="button" aria-label="Generate New Seed" data-action="diagnostics-retry-new-seed"${disabled(failure.canGenerateNewSeed)}>Generate New Seed</button>
      <button type="button" aria-label="Retry rendering" data-action="diagnostics-retry-geometry"${disabled(failure.canRetryGeometry)}>Retry rendering</button>
    </div>
  </div>`;
}

export function diagnosticsTrayHTML(entries: readonly Record<string, unknown>[], generation: GenerationState | null = null): string {
  const sections: string[] = [];
  const busy = generation?.active === true;
  const failure = generation !== null && generation.phase === "failed" ? generation.failure : null;
  if (failure !== null) sections.push(failureSectionHTML(failure, busy));
  const views = diagnosticViews(entries);
  const orphanSummary = orphanSummaryHTML(views);
  if (orphanSummary !== "") sections.push(orphanSummary);
  if (views.length > 0) {
    const items = views.map((view) => {
      const severity = view.severity === "error" ? "error" : "warning";
      const status = view.severity === "error" ? "Error" : "Warning";
      const label = view.subsystem === "city" ? "City" : view.subsystem;
      const identity = diagnosticIdentityHTML(view);
      return `<li data-severity="${severity}"><span class="nixie-diagnostic-status">${status}</span> <span>${escapeHTML(label)}: ${escapeHTML(view.message)}</span>${identity === "" ? "" : `<br>${identity}`}${view.retry === null ? "" : retryButtonHTML(view, busy)}</li>`;
    }).join("");
    sections.push(`<ul class="nixie-district-diagnostics">${items}</ul>`);
  }
  if (sections.length === 0) {
    return `<section data-panel="diagnostics" class="nixie-tray-inspector"><h3>Diagnostics</h3><p class="nixie-note">No diagnostics recorded. Failed or degraded structural or decorative generation, invalid-geometry rejections, and stale-editor rejections will be listed here.</p></section>`;
  }
  return `<section data-panel="diagnostics" class="nixie-tray-inspector"><h3>Diagnostics</h3>${sections.join("")}</section>`;
}

export interface DiagnosticsWorkspaceDeps {
  entries: () => Array<Record<string, unknown>>;
  generationState: () => GenerationState;
  retryWalls: () => Promise<unknown>;
  retryPlan: () => Promise<unknown>;
  retryGeometry: () => Promise<unknown>;
  retrySameSeed: () => Promise<unknown>;
  generateNewSeed: () => Promise<unknown>;
}

const defaultDeps: DiagnosticsWorkspaceDeps = {
  entries: diagnosticEntries,
  generationState,
  retryWalls: retryGeneratedWalls,
  retryPlan: retryDistrictPlan,
  retryGeometry,
  retrySameSeed: retryFullGeneration,
  generateNewSeed: () => generateNewSeed()
};

export function diagnosticsWorkspace(deps: Partial<DiagnosticsWorkspaceDeps> = {}): WorkspaceModule {
  const d: DiagnosticsWorkspaceDeps = { ...defaultDeps, ...deps };

  const runGeneration = (ctx: WorkspaceContext, work: Promise<unknown>): void => {
    void work
      .then(() => ctx.rerender())
      .catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        console.error("nixie | city generation retry failed", err);
        ui.notifications?.error(`Nixie: city generation retry failed — ${message}`);
        ctx.rerender();
      });
  };

  return {
    id: "diagnostics",
    renderShelf(): string {
      return "";
    },
    renderTray(): string {
      return diagnosticsTrayHTML(d.entries(), d.generationState());
    },
    onAction(action: string, _target: HTMLElement, ctx: WorkspaceContext): void {
      if (d.generationState().active) return;
      switch (action) {
        case "diagnostics-retry-walls":
          ctx.run("generated wall retry", d.retryWalls());
          return;
        case "diagnostics-retry-plan":
          ctx.run("district plan retry", d.retryPlan());
          return;
        case "diagnostics-retry-geometry":
          ctx.run("render retry", d.retryGeometry());
          return;
        case "diagnostics-retry-same-seed":
          runGeneration(ctx, d.retrySameSeed());
          return;
        case "diagnostics-retry-new-seed":
          runGeneration(ctx, d.generateNewSeed());
          return;
        default:
          return;
      }
    },
    onRender(_root: HTMLElement, _ctx: WorkspaceContext): void {}
  };
}
